# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: echo 'install helpful python libraries' # configure environment
    command: pip3 install pwntools
  - init: echo 'disable aslr'
    command: sudo bash -c 'echo 0 > /proc/sys/kernel/randomize_va_space'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
